Servicos\ApiBundle\Entity\Localizacoes\ViabilidadesDataCenter:
    type: entity
    oneToMany:
        pontos:
            targetEntity: Servicos\ApiBundle\Entity\Localizacoes\Pontos
            cascade:
                - persist
                - merge
            fetch: LAZY
            mappedBy: viabilidadesDataCenter
    lifecycleCallbacks: {  }
