Servicos\ApiBundle\Entity\Localizacoes\ViabilidadesCircuito:
    type: entity
    oneToMany:
        circulos:
            targetEntity: Servicos\ApiBundle\Entity\Localizacoes\Circulos
            cascade:
                - persist
                - merge
            fetch: LAZY
            mappedBy: viabilidadesCircuito
    lifecycleCallbacks: {  }
