Servicos\ApiBundle\Entity\Permissoes\Usuario:
    type: entity
    table: permissoes.usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        ativo:
            type: boolean
            nullable: false
            options:
                default: true
        removido:
            type: boolean
            nullable: false
            options:
                default: false
        dataCadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: data_cadastro
    manyToMany:
        grupCodigoid:
            targetEntity: Servicos\ApiBundle\Entity\Permissoes\Grupo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: usuaCodigoid
            joinTable:
                name: permissoes.usuario_grupo
                joinColumns:
                    -
                        name: usua_codigoid
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: grup_codigoid
                        referencedColumnName: grup_codigoid
            orderBy: null
        permCodigoid:
            targetEntity: Servicos\ApiBundle\Entity\Permissoes\Permissao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: usuaCodigoid
            joinTable:
                name: permissoes.usuario_permissao
                joinColumns:
                    -
                        name: usua_codigoid
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: perm_codigoid
                        referencedColumnName: perm_codigoid
            orderBy: null
    lifecycleCallbacks: {  }
