Servicos\ApiBundle\Entity\Pessoas\Pessoa2Pessoa:
    type: entity
    table: pessoas.pessoa_2_pessoa
    indexes:
        IDX_DB46491CC1E38874:
            columns:
                - pess_mandatario
        IDX_DB46491CA3854BA9:
            columns:
                - pess_subordinado
        IDX_DB46491C7A62B8C6:
            columns:
                - tiporela_codigoid
    id:
        pessMandatario:
            associationKey: true
        pessSubordinado:
            associationKey: true
        tiporelaCodigoid:
            associationKey: true
    fields:
        pess2pessAtivo:
            type: boolean
            nullable: false
            options:
                default: true
            column: pess2pess_ativo
        pess2pessRemovido:
            type: boolean
            nullable: false
            options:
                default: false
            column: pess2pess_removido
        pess2pessDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: pess2pess_datacadastro
    oneToOne:
        pessMandatario:
            targetEntity: Servicos\ApiBundle\Entity\Pessoas\Pessoa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pess_mandatario:
                    referencedColumnName: pess_codigoid
            orphanRemoval: false
        pessSubordinado:
            targetEntity: Servicos\ApiBundle\Entity\Pessoas\Pessoa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pess_subordinado:
                    referencedColumnName: pess_codigoid
            orphanRemoval: false
        tiporelaCodigoid:
            targetEntity: Servicos\ApiBundle\Entity\Pessoas\TipoRelacionamento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tiporela_codigoid:
                    referencedColumnName: tiporela_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
