Servicos\ApiBundle\Entity\Pessoas\Segmento:
    type: entity
    table: pessoas.segmento
    id:
        segmCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: segm_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        segmNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: segm_nome
        segmDescricao:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: segm_descricao
        segmAtivo:
            type: boolean
            nullable: false
            options:
                default: true
            column: segm_ativo
        segmRemovido:
            type: boolean
            nullable: false
            options:
                default: false
            column: segm_removido
        segmDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: segm_datacadastro
    lifecycleCallbacks: {  }
