Servicos\ApiBundle\Entity\Pessoas\TipoDocumento:
    type: entity
    table: pessoas.tipo_documento
    id:
        tipodocuCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: tipodocu_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        pessTipo:
            type: tipo_pessoa
            nullable: false
            column: pess_tipo
        tipodocuNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tipodocu_nome
        tipodocuDescricao:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: tipodocu_descricao
        tipodocuAtivo:
            type: boolean
            nullable: false
            options:
                default: true
            column: tipodocu_ativo
        tipodocuRemovido:
            type: boolean
            nullable: false
            options:
                default: false
            column: tipodocu_removido
        tipodocuDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: tipodocu_datacadastro
    lifecycleCallbacks: {  }
