Servicos\ApiBundle\Entity\Localidades\Cidade:
    type: entity
    table: localidades.cidade
    indexes:
        IDX_FFBD4B23AD0E497F:
            columns:
                - esta_codigoid
    id:
        cidaCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: cida_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        cidaNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: cida_nome
        cidaCodigoDiscagem:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
            column: cida_codigo_discagem
        cidaPoligono:
            type: polygon
            nullable: true
            requireSQLConversion: true
            column: cida_poligono
        cidaDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: cida_datacadastro
    manyToOne:
        estaCodigoid:
            targetEntity: Servicos\ApiBundle\Entity\Localidades\Estado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                esta_codigoid:
                    referencedColumnName: esta_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
