Servicos\ApiBundle\Entity\Localidades\Pais:
    type: entity
    table: localidades.pais
    id:
        paisCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: pais_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        paisNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: pais_nome
        paisAcronimo:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: pais_acronimo
        paisAcessoDdi:
            type: boolean
            nullable: false
            options:
                default: true
            column: pais_acesso_ddi
        paisCodigoDiscagem:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
            column: pais_codigo_discagem
        paisAtivo:
            type: boolean
            nullable: false
            options:
                default: true
            column: pais_ativo
        paisRemovido:
            type: boolean
            nullable: false
            options:
                default: false
            column: pais_removido
        paisPoligono:
            type: polygon
            nullable: true
            requireSQLConversion: true
            column: pais_poligono
        paisDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: pais_datacadastro
    lifecycleCallbacks: {  }
