Servicos\ApiBundle\Entity\Permissoes\Grupo:
    type: entity
    table: permissoes.grupo
    id:
        grupCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: grup_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        grupNome:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: grup_nome
        grupDescricao:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: grup_descricao
        grupDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: grup_datacadastro
    oneToMany:
        grupoPermissao:
            targetEntity: Servicos\ApiBundle\Entity\Permissoes\GrupoPermissao
            cascade:
                - persist
            fetch: LAZY
            mappedBy: grupCodigoid
    manyToMany:
        usuaCodigoid:
            targetEntity: Servicos\ApiBundle\Entity\Permissoes\Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: grupCodigoid
            inversedBy: null
            joinTable: null
            orderBy: null
        permCodigoid:
            targetEntity: Servicos\ApiBundle\Entity\Permissoes\Permissao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: grupCodigoid
            joinTable:
                name: permissoes.grupo_permissao
                joinColumns:
                    -
                        name: grup_codigoid
                        referencedColumnName: grup_codigoid
                inverseJoinColumns:
                    -
                        name: perm_codigoid
                        referencedColumnName: perm_codigoid
            orderBy: null
    lifecycleCallbacks: {  }
