Servicos\ApiBundle\Entity\Pessoas\TipoRelacionamento:
    type: entity
    table: pessoas.tipo_relacionamento
    id:
        tiporelaCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: tiporela_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        pessTipo:
            type: tipo_pessoa
            nullable: false
            column: pess_tipo
        tiporelaNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tiporela_nome
        tiporelaAtivo:
            type: boolean
            nullable: false
            options:
                default: true
            column: tiporela_ativo
        tiporelaRemovido:
            type: boolean
            nullable: false
            options:
                default: false
            column: tiporela_removido
        tiporelaDatacadastro:
            type: datetime
            nullable: false
            options:
                default: now()
            column: tiporela_datacadastro
    lifecycleCallbacks: {  }
