servicos_sso:
    type: rest
    resource: "@ServicosSsoBundle/Resources/config/routing.yml"
    prefix:   /auth

servicos_api:
    type: rest
    resource: "@ServicosApiBundle/Resources/config/routing.yml"
    prefix: /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation
