services:
    servicos_api.permissoes.grupos.criar:
        class: Servicos\ApiBundle\Service\Permissoes\Grupos\Criar
        lazy: true
        arguments: ["@doctrine"]
    servicos_api.permissoes.permissoes.criar:
        class: Servicos\ApiBundle\Service\Permissoes\Permissoes\Criar
        lazy: true
        arguments: ["@doctrine"]
    servicos_api.permissoes.usuario.criar:
        class: Servicos\ApiBundle\Service\Permissoes\Usuarios\Criar
        lazy: true
        arguments: ["@doctrine"]
        