services:
    servicos_api.permissoes.grupos.criar:
        class: Servicos\ApiBundle\Service\Permissoes\Grupos\Criar
        lazy: true
        arguments: ["@doctrine"]
    servicos_api.permissoes.permissoes.criar:
        class: Servicos\ApiBundle\Service\Permissoes\Permissoes\Criar
        lazy: true
        arguments: ["@doctrine"]
    servicos_api.permissoes.usuarios.criar:
        class: Servicos\ApiBundle\Service\Permissoes\Usuarios\Criar
        lazy: true
        arguments: ["@doctrine", "@security.password_encoder"]
    servicos_api.permissoes.usuarios.listar:
        class: Servicos\ApiBundle\Service\Permissoes\Usuarios\Listar
        lazy: true
        arguments: ["@doctrine"]
        