app_login:
    path:     /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods:  [GET]
    
app_login_check:
    path:     /login_check
    defaults: { _controller: "AppBundle:Default:loginCheck" }
    
app_logout:
    path:     /logout
    defaults: { _controller: "AppBundle:Default:logout" }
    
app_regitration:
    path:     /register
    defaults: { _controller: "AppBundle:Registration:register" }
    
app_welcome:
    path:     /welcome
    defaults: { _controller: "AppBundle:Index:welcome" }
    
app_usuarios:
    path:     /usuarios/view
    defaults: { _controller: "AppBundle:Permissoes/Usuarios/Default:default" }
    
app_localidades:
    path:     /localidades
    defaults: { _controller: "AppBundle:Localidades/Default:index" }
    